WIP: Améliorer la hiérarchisation des données dans la page de détail de candidature
gip-inclusion/les-emplois pull request #3508
Opened 2024-01-03 16:18 UTC by hellodeloo

**Carte Notion :** https://www.notion.so/plateforme-inclusion/2-3-page-candidature-Am-liorer-la-hi-rarchisation-des-donn-es-dans-la-page-de-d-tail-de-candidatur-9d17131d0d4641f291528720d1f9e867

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ? 

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran 

### À vérifier

- [ ] Ajouter l'étiquette « no-changelog » ?
- [ ] Mettre à jour le CHANGELOG_breaking_changes.md ?

2024-01-15 16:00 UTC, vincentporte commented on itou/templates/apply/includes/job_seeker_info.html
> +            <button class="btn-link" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-trigger="manual" data-bs-title="Copié!" data-it-clipboard-button="copy" data-it-copy-to-clipboard="{{ job
`{% matomo_event "candidature" "clic" "copied_jobseeker_email" %}` etc

2024-01-17 09:31 UTC, xavfernandez reviewed
Commits à squasher/regrouper entre eux

2024-01-17 09:31 UTC, xavfernandez commented on itou/templates/apply/includes/job_application_sender_info.html
> +                    {% matomo_event "candidature" "clic" "copied_sender_phonel" %}>
```suggestion
                    {% matomo_event "candidature" "clic" "copied_sender_phone" %}>
```

2024-01-17 09:31 UTC, xavfernandez commented on tests/www/apply/test_process.py
> +        self.assertNotContains(response, "<small\">Commentaire privé de l'employeur</small>")
```suggestion
        self.assertNotContains(response, "<small>Commentaire privé de l'employeur</small>")
```

2024-01-18 10:03 UTC, hellodeloo commented on itou/templates/apply/includes/job_application_sender_info.html
> +                    {% matomo_event "candidature" "clic" "copied_sender_phonel" %}>
Ooops

2024-01-18 10:07 UTC, hellodeloo commented on tests/www/apply/test_process.py
> +        self.assertNotContains(response, "<small\">Commentaire privé de l'employeur</small>")
Bien vu. curieux que les tests n'ont pas plantés

2024-01-18 10:43 UTC, hellodeloo commented on itou/templates/apply/process_details_company.html
>          {% include "apply/includes/job_seeker_info.html" with job_seeker=job_application.job_seeker job_application=job_application can_view_personal_information=can_view_personal_information can_edi
C'est pas déjà ajouté ? Genre ici ? https://github.com/gip-inclusion/les-emplois/blob/9541c48c5ff0dcab67423cb14b67236e92860ff9/itou/templates/apply/includes/job_application_diagoriente_invite.html#L17

2024-01-18 13:19 UTC, hellodeloo commented on itou/templates/apply/process_details_company.html
>          {% include "apply/includes/job_seeker_info.html" with job_seeker=job_application.job_seeker job_application=job_application can_view_personal_information=can_view_personal_information can_edi
Je pige aps trop ce qu'il faut faire ? Il faudrait enlever le `only` sur cette ligne ?
https://github.com/gip-inclusion/les-emplois/blob/9541c48c5ff0dcab67423cb14b67236e92860ff9/itou/templates/apply/process_details.html#L9

2024-01-18 13:21 UTC, xavfernandez commented on itou/templates/apply/process_details_company.html
>          {% include "apply/includes/job_seeker_info.html" with job_seeker=job_application.job_seeker job_application=job_application can_view_personal_information=can_view_personal_information can_edi
Soit enlever le `only` soit rajouter le `csrf_token=csrf_token`

2024-01-18 13:50 UTC, hellodeloo commented on itou/templates/apply/process_details_company.html
>          {% include "apply/includes/job_seeker_info.html" with job_seeker=job_application.job_seeker job_application=job_application can_view_personal_information=can_view_personal_information can_edi
ok j'ai ajouté csrf_token=csrf_token

2024-01-22 10:26 UTC, xavfernandez requested changes

2024-01-22 10:26 UTC, xavfernandez commented on itou/templates/apply/process_details_company.html
>          {% include "apply/includes/job_seeker_info.html" with job_seeker=job_application.job_seeker job_application=job_application can_view_personal_information=can_view_personal_information can_edi
là aussi il faut le csrf_token. Et dans `approvals/detail.html` qui include également `apply/includes/job_seeker_info.html` en mode `only`

2024-01-22 16:15 UTC, hellodeloo commented on itou/templates/apply/process_details_company.html
>          {% include "apply/includes/job_seeker_info.html" with job_seeker=job_application.job_seeker job_application=job_application can_view_personal_information=can_view_personal_information can_edi
Ah oui merci. Je l'ai fait aussi pour `apply/process_details_company.html` qui inclut aussi le  `job_seeker_info.html` en mode `only` et qui surement besoin du `csrf_token`

2024-01-23 14:31 UTC, xavfernandez approved these changes

2024-01-23 14:31 UTC, xavfernandez commented on itou/templates/apply/includes/job_application_sender_info.html
> +        </button>
Je tilte un peu tard mais pour les boutons copier on avait le template https://github.com/gip-inclusion/les-emplois/blob/master/itou/templates/includes/copy_to_clipboard.html qui utilise du JS maison alors qu'apparemment on peut s'en passer ?

2024-01-23 14:48 UTC, hellodeloo commented on itou/templates/apply/includes/job_application_sender_info.html
> +        </button>
@xavfernandez Je ne sais pas s'il sert encore ce bout de template. Je ne suis pas à l'origine et je ne sais pas trop à quoi il sert.

2024-01-23 14:49 UTC, xavfernandez commented on itou/templates/apply/includes/job_application_sender_info.html
> +        </button>
Oui il sert encore et permet d'avoir un bouton "Copier" comme ce que fait ton bouton.

2024-01-23 14:52 UTC, hellodeloo commented on itou/templates/apply/includes/job_application_sender_info.html
> +        </button>
Bon, on va le laisser alors. En espérant que par la suite, les différentes versions du "copy-clipboard" vont se réduire.

2024-01-23 15:27 UTC, merged