Stats : Publier le TB289 (Suivi des prescriptions des prescripteurs habilités) à 3 régions [GEN-3907]
gip-inclusion/les-emplois pull request #3576
Opened 2024-02-01 11:03 UTC by rsebille

### Pourquoi ?

Cibles : DREETS et DDETS IAE des 3 régions ci-dessous
- Pays-de-la-Loire
- Nouvelle-Aquitaine
- Ile-de-France

### Captures d'écran 

*Avec*
![image](https://github.com/gip-inclusion/les-emplois/assets/20045330/ae36b01a-15c1-45f8-97ac-466e180f5ebe)
![image](https://github.com/gip-inclusion/les-emplois/assets/20045330/47f9e047-7803-4d20-9879-d80943245636)

*Sans*
![image](https://github.com/gip-inclusion/les-emplois/assets/20045330/9d54989f-6ae0-45a4-85c5-a1dc116f579c)
![image](https://github.com/gip-inclusion/les-emplois/assets/20045330/56b79e6c-93ad-4988-8bb1-a43c70f06848)

### À vérifier

- [x] Ajouter l'étiquette « no-changelog » ?
- [x] Mettre à jour le CHANGELOG_breaking_changes.md ?

2024-02-06 17:20 UTC, dejafait requested changes
Deux demandes de changements mineurs et sinon LGTM. 👍

2024-02-06 17:20 UTC, dejafait commented on itou/www/dashboard/views.py
> +        "can_view_stats_ddets_iae_ph_prescription": stats_utils.can_view_stats_ddets_iae_ph_prescription(request),
Ce n'est pas nécessaire ici car `can_view_stats_ddets_iae_ph_prescription` implique toujours `can_view_stats_ddets_iae`. Autrement dit, c'en est toujours un sous cas. On a mis `can_view_stats_ddets_iae_aci` ici seulement parce que c'est un cas exotique tordu qui n'est justement pas toujours un sous cas de `can_view_stats_ddets_iae`. Bref, autant garder cette (longue) liste la plus courte possible.

2024-02-06 17:20 UTC, dejafait commented on itou/www/dashboard/views.py
> +        "can_view_stats_dreets_iae_ph_prescription": stats_utils.can_view_stats_dreets_iae_ph_prescription(request),
Même remarque.

2024-02-06 17:20 UTC, dejafait commented on itou/www/stats/urls.py
> +        views.stats_ddets_iae_ph_prescription,
Toutes les autres vues stats utilisent toujours un terme technique unique. Pourquoi ici en utiliser deux et introduire potentiellement de la confusion ? Je propose de ne garder que soit `ph_prescription` soit `authorized_prescriber_prescription` mais pas les deux. Je vote pour le premier. Bref `ddets/ph_prescription` pour être iso avec toutes les autres vues.

2024-02-06 17:20 UTC, dejafait commented on itou/www/stats/urls.py
> +        "dreets/authorized_prescriber_prescription",
Même remarque. `dreets/ph_prescription`

2024-02-07 10:09 UTC, rsebille commented on itou/www/dashboard/views.py
> +        "can_view_stats_ddets_iae_ph_prescription": stats_utils.can_view_stats_ddets_iae_ph_prescription(request),
Pas sûr de comprendre, dans `can_view_stats_ddets_iae_ph_prescription` il y a aussi la liste blanche de région donc `can_view_stats_ddets_iae` ne suffit pas.

2024-02-09 16:10 UTC, dejafait approved these changes
LGTM

2024-02-13 10:25 UTC, merged