Ajouter des context processors à www/error.py
gip-inclusion/les-emplois pull request #4077
Opened 2024-05-13 14:59 UTC by francoisfreitag

## :thinking: Pourquoi ?

Des échecs de test plus clairs.

2024-05-13 19:53 UTC, xavfernandez requested changes
Tu peux au passage enlever les `ignore_unknown_variable_template_error` de `tests/www/test_error.py`

2024-05-13 19:53 UTC, xavfernandez commented on itou/www/error.py
> +            | static(request)
Je ne vois pas où on utilise `STATIC_URL` ?

2024-05-14 07:29 UTC, francoisfreitag commented on itou/www/error.py
> +            | static(request)
En effet, on ne l’utilise pas. J’ai changé l’approche (qui inclut toujours `static(request)`).

Je me dis qu’on n’a pas vraiment de raison de ne pas inclure tous les `context_processors` ?

2024-05-14 07:38 UTC, xavfernandez commented on itou/www/error.py
> +            | static(request)
bah moins on a de code qui tourne, moins il y a de chances que ça plante.
Sinon, effectivement on se base sur `settings.TEMPLATES` pour tous les appeler.

2024-05-14 07:38 UTC, xavfernandez approved these changes

2024-05-14 07:43 UTC, francoisfreitag commented on itou/www/error.py
> +            | static(request)
Les `context_processors` sont appelés sur chaque requête qui rend un template, s’ils ne sont pas robustes, on va rapidement avoir des ennuis.

2024-05-15 09:37 UTC, merged