Contrôle a posteriori: Ajout d'un lien contacter le support si un prescripteur souhaite retirer des justificatifs attendus lors du contrôle [GEN-8]
gip-inclusion/les-emplois pull request #4187
Opened 2024-06-07 13:40 UTC by tonial

## :thinking: Pourquoi ?

Pour simplifier le support j'imagine :)

## :cake: Comment ? 

> _Décrivez en quelques mots la solution retenue et mise en oeuvre, les difficultés ou problèmes rencontrés. Attirez l'attention sur les décisions d'architecture ou de conception importantes._

## :computer: Captures d'écran 

## :rotating_light: À vérifier

- [ ] Mettre à jour le CHANGELOG_breaking_changes.md ?

## :desert_island: Comment tester

> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. Si vous disposez d'une recette jetable, mettre l'URL pour tester dans cette partie._

2024-06-10 06:57 UTC, xavfernandez approved these changes

2024-06-10 07:26 UTC, francoisfreitag requested changes
Ce message est prévu uniquement pour les DDETS et non les employeurs. La carte précise qu’il doit apparaître dans le template `siae_evaluation/institution_evaluated_job_application`.

STR :

1. test+cap@inclusion.beta.gouv.fr
2. Dashboard > Contrôle a posteriori
3. Sur chaque candidature, la mention est présente.

2024-06-10 07:26 UTC, francoisfreitag commented on itou/templates/siae_evaluations/includes/list_item.html
> +                Si vous estimez que certains critères ne sont pas nécessaires pour valider cette auto-prescription, <a href="{{ ITOU_HELP_CENTER_URL }}/requests/new" rel="noopener" target="_blank" ar
```suggestion
                Si vous estimez que certains critères ne sont pas nécessaires pour valider cette auto-prescription, <a href="{{ ITOU_HELP_CENTER_URL }}/requests/new" rel="noopener" target="_blank" aria-label="Contacter le support (ouverture dans un nouvel onglet)">veuillez contacter notre support technique.</a>
```

2024-06-13 16:09 UTC, francoisfreitag commented
Ce n’est toujours pas dans le bon template. C’est un message pour les DDETS, pas les SIAE.

2024-06-13 16:12 UTC, francoisfreitag approved these changes
![image](https://github.com/gip-inclusion/les-emplois/assets/2758243/bcb5d00b-f8de-4a59-b60e-c619f85c493e)

2024-06-14 06:55 UTC, merged