Candidature: Fix erreur 500 sur l'acceptation siae sous les conditions rares
gip-inclusion/les-emplois pull request #4522
Opened 2024-08-06 15:12 UTC by calummackervoy

## :thinking: Pourquoi ?

`CertifiedCriteriaInfoRequiredForm` utilise un champ `birthdate` qui est anticipé d'être une `date`, mais c'est dans l'utilisation c'est possible que c'est un `str`, qui cause un `ValueError`

## :cake: Comment ? 

* Enforcer que le `birthdate` dans `CertifiedCriteriaInfoRequiredForm` est une date
* Sur [_accept](https://github.com/gip-inclusion/les-emplois/compare/calum/fix-date-format?expand=1#diff-c4816cd2f94ad06618d8ec2ed19b7c4d7109a1fde13565b2f756b73e6c8da948), ratrappe le cas rare où le date est mis à jour en string, et le convertir
* Ajout des tests pour `CertifiedCriteriaInfoRequiredForm`

## :rotating_light: À vérifier

- [ ] Mettre à jour le CHANGELOG_breaking_changes.md ?

2024-08-07 05:05 UTC, tonial requested changes
Je pense que tu peux améliorer la façon dont on passe `birthdate` à `CertifiedCriteriaInfoRequiredForm`.
J'ai fait 2 propositions mais je ne suis pas encore sur de quelle est la meilleurs :thinking: cela peut valoir le coup d'en discuter rapidement en SU, ou de demander l'avis à d'autres dev.

Il faudrait également que tu ajoute un test dans `tests/www/apply/test_process.py::ProcessAcceptViewsTest` qui plante comme dans sentry avant ta correction car pour l'instant on ne garanti pas que le problème ne se reproduira pas : typiquement si quelqu'un rechange ton `birthdate = parse_date(birthdate)` aucun test ne casse.

2024-08-07 05:05 UTC, tonial commented on tests/www/apply/test_forms.py
> +    def test_cannot_use_form_with_non_date(self):
Je ne suis pas très convaincu par ces 2 derniers tests

2024-08-07 07:40 UTC, francoisfreitag commented on itou/www/apply/forms.py
> +            birthdate, datetime.date | datetime.datetime
Pour moi, pas la peine de mettre un assert qui nuit à la lisibilité. Le test ajouté devrait couvrir ce cas de figure, et au pire du pire Sentry nous informera.

2024-08-07 07:44 UTC, francoisfreitag commented on itou/www/apply/views/common.py
> +        if isinstance(birthdate, str):
C’est un probablement assez pénible vu la structure actuelle de la vue, mais on devrait valider le formulaire `JobSeekerPersonalDataForm()` et gérer le cas `form_personal_data.is_valid() is False`.
La solution proposée ci-dessus (`birthdate = JobSeekerPersonalDataForm.base_fields["birthdate"].clean( form_personal_data.data.get("birthdate"))`) va `raise ValidationError` si le champ est invalide.

Aussi, on ne profitera pas des validateurs (date dans le futur, date il y a moins de 18 ans, etc) en utilisant `parse_date`.

2024-08-07 08:18 UTC, calummackervoy commented on itou/www/apply/forms.py
> +            birthdate, datetime.date | datetime.datetime
@francoisfreitag le test ajouté cible l'utilisation courant mais je pense que cette assertion peut aider avec les prochaines utilisations de cette formulaire ? Dans ces cas c'est mieux d'être informé avec un AssertionError dans nos tests que d'attendre que c'est sur production

@tonial c'est bien possible de donner un `datetime` au champ `DateField` - e.g. `EmployerFactory(birthdate=timezone.now()).birthdate # datetime.date(2024, 8, 7)`

2024-08-07 08:41 UTC, calummackervoy commented on itou/www/apply/views/common.py
> +        if isinstance(birthdate, str):
OK ! J'ai choisis cette approche parce qu'il change très peu le dessin existant - en faveur de juste le rendre plus explicite - j'ai reflechis que ce serait meilleur d'avoir le `birthdate` validée, mais j'ai vu aussi que ça vient d'un widget dont on peut avoir confiance

J'avais pas reflechis aux autres validateurs par contre - et je suis d'accord, merci 👍

2024-08-07 08:47 UTC, calummackervoy commented on tests/www/apply/test_forms.py
> +    def test_cannot_use_form_with_non_date(self):
`test_cannot_use_form_with_non_date` est peut-être superflu ?

`test_job_seeker_personal_data_compatible_with_form` est inclu pour montrer que ce code ajouté fixe l'erreur actuel du PR. Il n'utilise pas la structure des formulaires / vues qui cause la situation mais je pensais qu'il était suffisant ?

J'ai pas tenté de couvrir plus des cas que ces impliqués par l'erreur et la fixe

2024-08-07 08:59 UTC, francoisfreitag commented on itou/www/apply/forms.py
> +            birthdate, datetime.date | datetime.datetime
Pour moi, les `assert` sont quand on a une pré-condition critique à vérifier. Du genre “cette condition ne devrait jamais arriver, vérifions que l’appel à cette méthode est correct (sinon, c’est grave et mieux vaut exploser que de continuer avec une valeur incorrecte)”.

L’`assert` proposé causera également une 500 en prod (sauf si on lance python avec `-O`, qui enlève les `assert`...)
Pour le déclencher, il faut que le développeur se place dans le scénario précis dans son environnement de dev (c’est à dire passer une date de naissance `str` au formulaire). S’il est dans ce scénario, il verra l’exception, et donc l’assert ne fera que changer la cause de la 500 en la rendant moins claire.

2024-08-07 09:03 UTC, calummackervoy commented on itou/www/apply/forms.py
> +            birthdate, datetime.date | datetime.datetime
OK ça me va !

2024-08-07 09:43 UTC, calummackervoy commented on tests/www/apply/test_forms.py
> +    def test_cannot_use_form_with_non_date(self):
Je les supprimes parmi d'autres changements

2024-08-07 11:42 UTC, celine-m-s commented on tests/www/apply/test_forms.py
> +        assert form.errors["birth_place"] == [expected_msg]
Merci pour les tests sur le formulaire !

2024-08-07 11:44 UTC, celine-m-s approved these changes
Merci beaucoup ! :tada:

2024-08-07 14:09 UTC, francoisfreitag commented on itou/www/apply/views/common.py
> +            pass  # will be presented to user later
Pourquoi ne pas faire `if form_personal_data.is_valid():` ?

2024-08-07 14:52 UTC, calummackervoy commented on itou/www/apply/views/common.py
> +            pass  # will be presented to user later
Pour éviter qu'un autre champ invalide va empêcher la validation du `birth_place` sur `CertifiedCriteriaInfoRequiredForm`

2024-08-07 15:47 UTC, francoisfreitag commented on itou/www/apply/views/common.py
> +            pass  # will be presented to user later
Ok. C’est plus compliqué que nécessaire pour un cas très à la marge, mais comme tu préfères.

2024-08-07 15:54 UTC, francoisfreitag commented
Attention, le titre des PRs est utilisé pour communiquer les changements au utilisateurs. Mieux vaut le reformuler pour expliquer un peu plus ce qui a été changé (notamment erreur 500 qui n’est pas très parlant)

2024-08-07 15:58 UTC, francoisfreitag approved these changes
Autrement LGTM, merci d’avoir fixé le problème :100:

2024-08-08 05:30 UTC, tonial commented on itou/www/apply/forms.py
> +            birthdate, datetime.date | datetime.datetime
@calummackervoy attention : l'objet python est construit à partir des données passées en argument à la factory.
Si tu fais `EmployerFactory(birthdate="2024-08-07")` ce sera une `str`.
Par contre une fois que tu fais un `user.refresh_from_db()` ce sera bien une date.

2024-08-08 05:31 UTC, tonial approved these changes
Super !

2024-08-08 08:20 UTC, merged