wip: add batch processing for applications
gip-inclusion/les-emplois pull request #5089
Opened 2024-11-12 16:06 UTC by hellodeloo

## :thinking: Pourquoi ?

> _Indiquez le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements._

## :cake: Comment ? 

> _Décrivez en quelques mots la solution retenue et mise en oeuvre, les difficultés ou problèmes rencontrés. Attirez l'attention sur les décisions d'architecture ou de conception importantes._

## :rotating_light: À vérifier

- [ ] Mettre à jour le CHANGELOG_breaking_changes.md ?

## :desert_island: Comment tester

> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. Si vous disposez d'une recette jetable, mettre l'URL pour tester dans cette partie._

## :computer: Captures d'écran

2024-12-03 15:03 UTC, francoisfreitag commented on itou/templates/apply/includes/list_tr.html
> +                    {% for job in all_jobs %}<li>{{ job.display_name }}</li>{% endfor %}
J’imagine qu’on aura besoin d’un collapse ici à un moment ?

2024-12-03 15:12 UTC, francoisfreitag commented on tests/www/apply/test_list_for_job_seeker.py
> +    ]:
À mon avis, un test dédié suffirait. Les filtres étant indépendant, on pourrait tester toutes les combinaisons de cette manière, ce qui serait un beau bazar et prendrait des plombes.

En revanche, j’ajouterais bien le cas `{"display": "invalid"}` au test spécifique.

2024-12-03 15:38 UTC, xavfernandez commented on itou/static/js/utils.js
> +
Je me demandais si on voulait pas généraliser son utilisation dans tout le fichier à la place d'un simple `target.querySelectorAll`.
Car quand on veut réinitialiser le JS sur une élément swappé et que cet élément swappé est à la racine (comme les boutons Liste/Tableau dans mon cas), c'est assez piégeux.

2024-12-03 15:49 UTC, xavfernandez commented on itou/templates/apply/includes/list_job_applications.html
> +                <table class="table table-hover">
Quand je lis https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role#description :
`If presentation or none is applied to a <table> element, the descendant <caption>, <thead>, <tbody>, <tfoot>, <tr>, <th>, and <td> elements inherit the role and are thus not exposed to assistive technologies.`
Ça voudrait dire que le `<caption>` juste en dessous ne servirait plus ?

2024-12-03 16:05 UTC, xavfernandez commented on itou/static/js/utils.js
> +  })
Yup, les lignes cliquables dans les tableaux, le HTML n'a pas été fait pour :grimacing: 
Mais je crois que le métier y tient et tant qu'on ne rajoute rien de cliquable dans les lignes, ça devrait bien se passer :crossed_fingers: ?

2024-12-03 16:08 UTC, xavfernandez commented on tests/www/apply/test_list_for_job_seeker.py
> +    ]:
J'ai hésité et bonne idée pour le `{"display": "invalid"}`. Par contre, comme je ne pense pas que vérifier la présence d'un `<caption class="visually-hidden">Liste des candidatures</caption>` ou d'un `<div class="c-box c-box--results has-links-inside my-3 my-md-4">` soit un super test, je vais juste intégrer cela dans le test de snapshot.

2024-12-03 16:52 UTC, francoisfreitag commented on itou/static/js/utils.js
> +  })
On ne va pas rajouter d’ici quelques jours un `<input type="checkbox">` ?

Pour moi, on dit devrait expliquer au métier que ce n’est pas possible techniquement (on ne veut pas avoir à devenir si l’utilisateur voulait cliquer sur la ligne ou le contrôle) et pas une bonne idée. Plusieurs conventions assez universelles du web et d’accessibilité (lien qui s’affiche au survol de la souris, éléments interactifs mis en surbrillance/focusable) sont bafouées.

2024-12-03 16:58 UTC, francoisfreitag commented on itou/static/js/utils.js
> +
J’aurais tendance à dire non. `querySelectorAll` cherche les nœuds descendants, donc il me paraît clair qu’on n’aura pas `target`. Pour initialiser le JS sur l’élément swappé, il suffit de passer `target` à la fonction d’init à appeler, pas besoin de passer par un `querySelectorAll`.

2024-12-03 17:00 UTC, francoisfreitag commented on tests/www/apply/test_list_for_job_seeker.py
> +    ]:
Je voulais dire d’écrire un test qui vérifie le contenu de la page sans filtres avec des candidatures, en faisant `display=list` et `display=table`. Plutôt que de se brancher sur des tests existants qui vérifient le fonctionnement d’autres filtres et de les rendre plus complexes et plus lents.

2024-12-03 17:12 UTC, hellodeloo commented on itou/static/js/utils.js
> +  })
@francoisfreitag J'ai déjà argumenté mon possible, mais sans succès 😔 
Pour le `<th scope="row"><input type="checkbox"></th>`, il sera cliquable séparément de la ligne, c'est déjà prévu dans le css

2024-12-04 08:44 UTC, francoisfreitag requested changes
https://github.com/gip-inclusion/les-emplois/pull/5089#discussion_r1868976865

2024-12-04 09:33 UTC, xavfernandez commented on itou/static/js/utils.js
> +
L'idée c'est d'avoir le même JS qui gère les deux cas:
- chargement d'une page de 0 (et l'élément à initialiser est bien un noeud descendant, donc `querySelectorAll` marche bien)
- chargement lors d'un `hx-swap-oob` (et l'élément à initialiser est maintenant `target` donc `querySelectorAll` ne marche plus)

Il se trouve qu'actuellement nos éléments swappés sont souvent dans des `div` correspondant à une zone et donc le JS à initialiser n'est que rarement sur l'élément swappé.
Mais il suffit qu'un dev se dise qu'il est inutile de swapper le `div` et que swapper le `form` serait plus efficace (car ma foi, le `div` ne change pas en fait !): hop le JS censé initialiser le `form` ne fonctionnera plus.

2024-12-04 10:00 UTC, xavfernandez commented on itou/templates/apply/includes/list_job_applications.html
> +                <table class="table table-hover">
Du coup, on n'a pas envie de ce `role="presentation"` ?

2024-12-06 11:00 UTC, francoisfreitag commented on itou/static/js/utils.js
> +
Je vois l’idée, ça évitera sûrement des erreurs.

Je pense toujours que la fonction ne devrait pas être globale (mais déclarée dans le `htmx.onLoad()` ou une IIFE qui enregistre le `htmx.onLoad()`) ce qui était le but de mon commentaire initial.

Et du coup, plutôt pour une PR séparée qui promeut l’utilisation de `querySelectorAllIncludingTarget` dans ce module.

2024-12-09 16:46 UTC, francoisfreitag commented on itou/static/js/utils.js
> +
À ne pas rater au rebase.

2024-12-09 16:55 UTC, francoisfreitag approved these changes
Super :+1:

2024-12-09 16:55 UTC, francoisfreitag commented on tests/www/apply/test_list_for_siae.py
> +        )
Pas de changements nécessaires sur cette ligne.

2024-12-09 20:09 UTC, xavfernandez commented on itou/static/js/utils.js
> +
Bien vu, je l'avais effectivement raté :grimacing:

2024-12-10 08:01 UTC, merged