Tech : Correction d'un test bagottant
gip-inclusion/les-emplois pull request #5311
Opened 2024-12-23 18:59 UTC by rsebille

## :thinking: Pourquoi ?

https://github.com/gip-inclusion/les-emplois/actions/runs/12470779088/job/34806524412?pr=5249
Introduit (vicieusement) dans #5295.

2024-12-24 08:27 UTC, xavfernandez commented on tests/metabase/management/test_populate_metabase_emplois.py
> +            timezone.localdate(job_application_2.eligibility_diagnosis.created_at, timezone=datetime.UTC),
Pourquoi UTC ? Si on veut la date de création du diag, cela me semble plus logique de convertir le timestamp en se basant sur Europe/Paris non ?

2024-12-24 13:50 UTC, rsebille commented on tests/metabase/management/test_populate_metabase_emplois.py
> +            timezone.localdate(job_application_2.eligibility_diagnosis.created_at, timezone=datetime.UTC),
Venant du modèle, `created_at` est un `datetime.datetime` avec la TZ "Europe/Paris".
De ce que j'ai compris là où ça part en eau de boudin c'est après, la table ainsi que les données sont créées directement _via_ `psycopg` ce qui fait qu'_a priori_ la TZ n'est pas configurée au niveau de la connexion (ce qui est le cas pour `django.db.connection` qu'on utilise pour lire les données) donc on est en UTC mais on envois un _timestamptz_ donc PG fait la conversion :
```
postgres@127.0.0.1:itou=# SHOW TIMEZONE;
 Etc/UTC
postgres@127.0.0.1:itou=# SELECT '2024-11-06 00:30:00+00'::timestamptz::date;
 2024-11-06
postgres@127.0.0.1:itou=# SELECT '2024-11-06 00:30:00+01'::timestamptz::date;
 2024-11-05
```
```
postgres@127.0.0.1:itou=# SHOW TIMEZONE;
 Europe/Paris
postgres@127.0.0.1:itou=# SELECT '2024-11-06 00:30:00+00'::timestamptz::date;
 2024-11-06
postgres@127.0.0.1:itou=# SELECT '2024-11-06 00:30:00+01'::timestamptz::date;
 2024-11-06
```
On se retrouve donc avec la date UTC et non pas `Europoe/Paris` stockée dans la DB, vu que beaucoup de tests du fichier mentionne explicitement la TZ UTC au moment des comparaisons c'est (j'espère) le comportement voulu, et quitte à faire une erreur autant qu'elle soit (à peu près) la même partout, mais oui c'est pas ouf...

2024-12-30 16:15 UTC, celine-m-s approved these changes

2025-01-06 10:52 UTC, xavfernandez commented on tests/metabase/management/test_populate_metabase_emplois.py
> +            timezone.localdate(job_application_2.eligibility_diagnosis.created_at, timezone=datetime.UTC),
Ça ne me choque pas de stocker la date en UTC.
Mais quand on demande à quelle date a été créé un diagnostic, cela me semble plus logique de répondre en utilisant la TZ Europe/Paris. Mais du coup l'erreur originelle vient de https://github.com/gip-inclusion/les-emplois/blob/b47fe4a2caf08d84e2d3cd7e7c0d1fc3431cab04/itou/metabase/tables/job_seekers.py#L297

2025-01-06 11:13 UTC, rsebille commented on tests/metabase/management/test_populate_metabase_emplois.py
> +            timezone.localdate(job_application_2.eligibility_diagnosis.created_at, timezone=datetime.UTC),
Si la logique était de stocker les dates en `Europe/Paris`, alors oui.
Par contre cette situation et conversion arrive aussi pour plein d'autres champs donc la logique, par voie de fait, est actuellement de stocker les dates en `UTC`.
Je doute qu'on se lance dans ce changement/correction à plus ou moins court terme car un certain nombre de ces champs ne devraient pas être tronqué en fait, mais derrière ça veux dire tout adapter dans les modèles DBT et metabase :sweat:.

2025-01-06 12:23 UTC, xavfernandez approved these changes
Ça devrait effectivement corriger le test mais je maintiens que c'est le code qui devrait être corrigé: passer un `datetime` à postgresql pour qu'il remplisse un champ `date` ne me semble pas être une bonne idée.

2025-01-06 14:03 UTC, francoisfreitag requested changes
Je suis d’accord avec Xavier : https://github.com/gip-inclusion/les-emplois/pull/5338
:innocent:

2025-01-06 14:35 UTC, rsebille commented
> Je suis d’accord avec Xavier : #5338 😇

Je ne suis pas en désaccord, mais *quasiment tout* les champs `"type": "date"` de la synchro sont dans ce cas donc ça m'embête de ne pas tous les accorder ensemble, encore plus quand d'autres champs de la même table sont également concernés.
Et vu que je ne suis pas encore descendu dans le trou de terrier de regarder ce qu'on en fait dans les modèles DBT et encore moins ce que Metabase en fait ensuite, ça me semble préférable d'avoir une logique peut-être erronée mais cohérente (et "explicable") que de changer des bouts par-ci par-là.

2025-01-06 15:08 UTC, francoisfreitag commented
C’est sûr qu’utiliser `timestamp with timezone` serait encore mieux, mais ça risque de casser pas mal de choses...

2025-01-07 13:30 UTC, rsebille commented
> C’est sûr qu’utiliser `timestamp with timezone` serait encore mieux, mais ça risque de casser pas mal de choses...

Oui, quitte à corriger ça me semble préférable que le production (les emplois) envois la donnée la plus précise sans trop réfléchir et que ça soit le consommateur qui décide (que ça soit la précision ou la _timezone_) comment il l'utilise, moins de responsabilité, moins de problèmes :).
En soit il y a rien de bien compliqué techniquement que ça soit coté emplois ou pilotage, faut juste s'y mettre et tirer les fils mais donc ça prend un peu plus de temps ;), pour ça que corriger le test en attendant me semblais être le bon compromis.

2025-01-07 13:50 UTC, francoisfreitag commented
Je proposerais bien le compromis suivant :
Localiser la date, ce qui ne devrait rien casser au pilotage et corriger quelques erreurs (je suppose rarissimes) de chiffres. Le jour où l’info plus précise est nécessaire, il sera intéressant d’étudier les ramifications du changement de type de données.

Qu’en penses-tu ?

2025-01-08 08:14 UTC, rsebille commented
> Je proposerais bien le compromis suivant : Localiser la date, ce qui ne devrait rien casser au pilotage et corriger quelques erreurs (je suppose rarissimes) de chiffres. Le jour où l’info plus précise est nécessaire, il sera intéressant d’étudier les ramifications du changement de type de données.
> 
> Qu’en penses-tu ?

Si tu veux.

2025-01-09 11:29 UTC, closed without merging