Amélioration du tunnel d'inscription des prescripteurs
gip-inclusion/les-emplois pull request #923
Opened 2021-10-19 09:10 UTC by SebastienReuiller

### Quoi ?

Simplification de l'inscription des prescripteurs

### Pourquoi ?

Pour fluidifier l'inscription des prescripteurs tout en évitant les doublons

### Comment ?

En supprimant des étapes et en améliorant celles requises.

### Captures d'écran 

La première étape :

![La première étape](https://user-images.githubusercontent.com/17601807/137878629-15eb1d5f-cf95-4485-8e1c-c230bcd9e27e.png)

Si des organisations correspondent au même SIRET ou au même SIREN sur le département sélectionné : 

![Des organisations correspondent](https://user-images.githubusercontent.com/17601807/137878840-186bc4b6-1e9c-4e17-9b5b-dffb229e980c.png)

Le message d'erreur si on tente de créer une organisation avec un même type et même SIRET en outrepassant la première étape : 

![Message d'erreur](https://user-images.githubusercontent.com/17601807/137878951-437b9e58-ce73-45df-85e6-978d89df0bfe.png)

La dernière étape avec rappel de l'organisation et de son type : 

![inscription_prescripteur_derniere_etape](https://user-images.githubusercontent.com/17601807/137879316-42ff38b3-dad7-43db-9164-deb4099e4859.png)

2021-10-19 10:11 UTC, madjid-asa approved these changes
Petite suggestion mais vraiment facultative :) 
Sinon great job! ça m'a permis d'apprendre le fonctionnement du tunnel d'inscription des prescripteurs 🎉

2021-10-19 10:11 UTC, madjid-asa commented on itou/www/signup/views.py
>              next_url = reverse("signup:prescriber_confirm_authorization")
```suggestion
        next_url = reverse( "signup:prescriber_user" if prescriber_kind == form.KIND_AUTHORIZED_ORG  else "signup:prescriber_confirm_authorization" )
```

2021-10-19 10:11 UTC, madjid-asa commented on itou/www/signup/views.py
>          elif prescriber_kind == form.KIND_UNAUTHORIZED_ORG:
```suggestion
        if prescriber_kind == form.KIND_UNAUTHORIZED_ORG:
```

2021-10-19 14:40 UTC, SebastienReuiller commented on itou/www/signup/views.py
>              next_url = reverse("signup:prescriber_confirm_authorization")
Effectivement, le ternaire ici permet d'éviter une affectation mais pour le coup, tu as inversé la condition ;)

2021-10-19 15:43 UTC, kemar requested changes
Presque bon pour moi.

2 typos, envisager un include au niveau du template et quelques questions.

2021-10-19 15:43 UTC, kemar commented on itou/www/signup/views.py
> +    prescriber_orgs_with_members_same_siren = None
Réflexion au passage. C'est quand même bizarre de demander en entrée un SIRET de 14 chiffres et de suggérer dans la foulée des résultats basés sur le SIREN.

Est-ce qu'on ne devrait pas laisser la possibilité de saisir un SIREN ou un SIRET ? Ça laisserait plus de latitudes aux usagers.

2021-10-19 15:43 UTC, kemar commented on itou/www/signup/views.py
> +        if hasattr(form, "org_data"):
Pourquoi faut-il un `if` ici ? Je me dis que si on sort du formulaire sans attribut `org_data`, alors on a un problème non ?

2021-10-19 15:43 UTC, kemar commented on itou/templates/signup/prescriber_check_already_exists.html
> +            <p>Par mesure sécurité, vous devez obtenir une invitation pour rejoindre une organisation déjà inscrite.</p>
```suggestion
            <p>Par mesure de sécurité, vous devez obtenir une invitation pour rejoindre une organisation déjà inscrite.</p>
```

Il manque un mot ici.

2021-10-19 15:43 UTC, kemar commented on itou/templates/signup/prescriber_check_already_exists.html
> +            <p>Par mesure sécurité, vous devez obtenir une invitation pour rejoindre une organisation déjà inscrite.</p>
```suggestion
            <p>Par mesure de sécurité, vous devez obtenir une invitation pour rejoindre une organisation déjà inscrite.</p>
```

Les résultats SIREN et SIRET ont l'air d'être exactement le même bloc de code qu'au dessus, si c'est le cas ça vaudrait le coup de faire un _include_ avec cette partie en sortant juste le titre.

2021-10-19 15:43 UTC, kemar commented on itou/www/signup/views.py
> +        self.kind_label = dict(PrescriberOrganization.Kind.choices).get(kind)
```suggestion
        self.kind_label = PrescriberOrganization.Kind[kind].label
```

Alternative pour le fun :)

2021-10-19 15:43 UTC, kemar commented on itou/www/signup/views.py
> +    As 80% of prescribers on Itou are Pôle emploi members, a link is dedicated for users who work for PE.
Pour 80% des gens, le lien est pas super visible :trollface:

2021-10-21 09:43 UTC, SebastienReuiller commented on itou/templates/signup/prescriber_check_already_exists.html
> +            <p>Par mesure sécurité, vous devez obtenir une invitation pour rejoindre une organisation déjà inscrite.</p>
Merci ! Tu te demandes des fois comment tu peux ne pas l'avoir vu en le tapant et en relisant..

2021-10-26 07:27 UTC, merged